all:
	make -C ../CommonLibStatic
	make -C ../ViewSynLibStatic
	make -C ../ViewSyn

debug:
	make -C ../CommonLibStatic debug
	make -C ../ViewSynLibStatic debug
	make -C ../ViewSyn debug

release:
	make -C ../CommonLibStatic release
	make -C ../ViewSynLibStatic release
	make -C ../ViewSyn release

clean:
	make -C ../CommonLibStatic clean
	make -C ../ViewSynLibStatic clean
	make -C ../ViewSyn clean
